### ISSUE TITLE
Add exact cuts pruning

### ISSUE THREAD

**Issue by frapac** [JuliaPolyhedra/CutPruner.jl#11]
Test which cuts are dominated with a LP problem. The advantage of this test is that it is exact and does not remove non-dominated cuts. 

The discussion is open to state whether to use Polyhedra.jl or JuMP plus a given LP solver

**Comment by blegat** [comment]
In [Polyhedra](https://github.com/JuliaPolyhedra/Polyhedra.jl), you can ask to remove redundant inequalities of a `Polyhedron`. If the library implements it then we leave it to the library. Otherwise we fallback to solving an LP per inequality to check whether it is redundant. If solving an LP is implemented in the library, we leave the LP-solving to the library. Otherwise we fallback to using MathProgBase to do solve the LPs.
I would be tempted to use this mechanism. When the user creates the exact cut pruner, he can give the Polyhedra Library as argument. If he chooses [SimplePolyhedraLibrary](https://github.com/JuliaPolyhedra/Polyhedra.jl/blob/master/src/simplepolyhedron.jl) or [ConvexHull](https://github.com/JuliaPolyhedra/ConvexHull.jl) then MPB will be used as a fallback but if he uses [CDDLib](https://github.com/JuliaPolyhedra/CDDLib.jl), [LRSLib](https://github.com/JuliaPolyhedra/LRSLib.jl) or [QHull](https://github.com/JuliaPolyhedra/QHull.jl) then the method implemented in the respective libraries will be used.

**Comment by blegat** [comment]
Do you want this to happen before v0.0.1 ?

**Comment by frapac** [comment]
I think that we can wait till version 0.0.2.

**Comment by frapac** [comment]
Solved with #16
